name: woocommerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  #对话框
  adaptive_dialog: ^1.6.4
  #轮番
  card_swiper: ^2.0.3
  #常用工具类，eg.双精度计算
  common_utils: ^2.1.0
  cupertino_icons: ^1.0.2
  #输入框时间选择器
  datetime_picker_formfield: ^2.0.0
  dependencies: any
  #网络请求
  dio: ^4.0.6
  flutter:
    sdk: flutter
  #加载框  
  flutter_easyloading: ^3.0.5
  #上拉加载下拉刷新
  flutter_easyrefresh: ^2.2.1
  #配置应用图标
  flutter_launcher_icons: ^0.9.3
  #本地化
  flutter_localizations:
    sdk: flutter
  #paypal支付  
  flutter_paypal: ^0.0.8
  #状态管理
  get: ^4.6.5
  #本地存储
  get_storage: ^2.0.3
  #国际化和本地化
  intl: ^0.17.0
  #骨架屏
  skeletons: ^0.0.3
  #权限助手
  permission_handler: ^10.0.0
  #打开URL/打电话
  url_launcher: ^6.1.2
  #高德定位
  amap_flutter_location: ^3.0.0

flutter_icons:
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  android: true 
  ios: true 

flutter_native_splash:
  color:"#42a5f5"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  assets:
    - images/
  uses-material-design: true
